FROM mysql:latest

MAINTAINER sangyeon <sovietist@hotmail.com>

ENV MYSQL_DATABASE tg
ENV MYSQL_USER tg
ENV MYSQL_PASSWORD 1q2w3e
ENV MYSQL_ROOT_PASSWORD 1q2w3e
						
EXPOSE 3306/tcp
    
CMD ["mysqld"]